name: nucleus_ui
description: Nucleus UI components for Flutter, fully customizable.
version: 0.0.1
homepage: https://nucleus-plus.web.app/
repository: https://github.com/nucleusui/nucleus-plus
documentation: https://nucleus-plus.web.app/
issue_tracker: hthttps://github.com/nucleusui/nucleus-plus/issues
topics:
  - user-interface
  - design-system

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 100
        - asset: fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 900
  uses-material-design: true
