name: nucleus_ui
description: Nucleus UI components for Flutter, fully customizable.
version: 0.0.1
homepage: https://nucleus-plus.web.app/
repository: https://github.com/nucleusui/nucleus-plus
documentation: https://nucleus-plus.web.app/
issue_tracker: hthttps://github.com/nucleusui/nucleus-plus/issues
topics:
  - user-interface
  - design-system

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  just_the_tooltip: ^0.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Figtree
      fonts:
        - asset: fonts/Figtree-Light.ttf
          weight: 100
        - asset: fonts/Figtree-Light.ttf
          weight: 200
        - asset: fonts/Figtree-Light.ttf
          weight: 300
        - asset: fonts/Figtree-Regular.ttf
          weight: 400
        - asset: fonts/Figtree-Medium.ttf
          weight: 500
        - asset: fonts/Figtree-SemiBold.ttf
          weight: 600
        - asset: fonts/Figtree-Bold.ttf
          weight: 700
        - asset: fonts/Figtree-ExtraBold.ttf
          weight: 800
        - asset: fonts/Figtree-Black.ttf
          weight: 900
